name: Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
permissions:
  contents: read
jobs:
  MACOS_M1:
    runs-on: macos-14
    env:
      CFLAGS: '-fsanitize=address,undefined'
      CPATH: /opt/homebrew/include
      LIBRARY_PATH: /opt/homebrew/lib
    steps:
      - uses: actions/checkout@v3
      - name: brew
        run: brew install capstone
      - name: make
        run: make CC=cc TARGET=aarch64 all
      - name: test
        run: make CC=cc TARGET=aarch64 test-ci
